#'SetBiomassExpParamsFun
#'
#' @description Function to take an EvFile Export object and set the export parameters within it
#' 
#' @param Obj_ExpVar- an Evfile export object of the form EVfile[['Properties']][['Export']][['Variables']]
#' 
#' @example SetBiomassExpParamsFun(Obj_ExpVar)
#' 
#' @export
SetBiomassExpParamsFun<-function(Obj_ExpVar){
  
##exports to turn on
Obj<-Obj_ExpVar$Item("Date_S")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Lat_S")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Lon_S")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Num_intervals")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Num_layers")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Time_S")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("VL_start")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("VL_end")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Exclude_above_line_depth_mean")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Exclude_below_line_depth_mean")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("First_layer_depth_start")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Last_layer_depth_stop")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Layer_depth_max")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Layer_depth_min")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("EV_filename")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Processing_date")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Processing_time")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Processing_version")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("PRC_NASC")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("NASC")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Standard_deviation")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Sv_mean")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Alpha")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Exclude_above_line_applied")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Exclude_below_line_applied")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Gain_constant")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Maximum_integration_threshold")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Minimum_integration_threshold")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Maximum_Sv_threshold_applied")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Minimum_Sv_threshold_applied")
Obj[["Enabled"]]<-TRUE
Obj<-Obj_ExpVar$Item("Noise_Sv_1m")
Obj[["Enabled"]]<-TRUE


## exports to turn off
Obj<-Obj_ExpVar$Item("Date_M")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Dist_M")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Dist_S")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Dist_E")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Depth_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Frequency")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Date_E")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Time_E")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Lat_M")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Lon_M")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Lat_E")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Lon_E")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("VL_mid")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Ping_E")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Ping_S")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Ping_M")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Region_detection_settings")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Region_notes")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Time_M")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bad_data_empty_water_samples")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bad_data_no_data_samples")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Exclude_below_line_depth_max")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Exclude_below_line_depth_min")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Exclude_below_line_range_min")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Exclude_below_line_range_max")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Grid_reference_line")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Heave_max")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Heave_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Heave_source")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Heave_min")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Layer_bottom_to_reference_line_depth")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Layer_bottom_to_reference_line_range")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Layer_top_to_reference_line_depth")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Layer_top_to_reference_line_range")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("No_data_samples")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Samples_Below_Bottom_Exclusion")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Samples_Above_Surface_Exclusion")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Samples_In_Domain")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Wedge_volume_sampled")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Exclude_above_line_range_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Exclude_below_line_range_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Height_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Range_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Thickness_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Program_version")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bottom_hardness_normalized")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bottom_kurtosis")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bottom_line_depth_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bottom_max_sv")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bottom_rise_time_normalized")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bottom_roughness_normalized")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bottom_skewness")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("First_bottom_length_normalized")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Second_bottom_length_normalized")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Density_number")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Density_weight")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Distance_3D_unsmoothed")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Fish_track_change_in_depth")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Fish_track_change_in_range")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Speed_4D_mean_unsmoothed")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Time_in_beam")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bin_count")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("3D_school_volume")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Corrected_length")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Corrected_thickness")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Num_targets")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Target_depth_max")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Target_depth_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Target_depth_min")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Target_range_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("TS_mean")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("ABC")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("ABC_noise")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("PRC_ABC")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Skewness")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Sv_min")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Sv_max")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Sv_noise")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Beam_volume_sum")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Good_Samples")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Bottom_offset")
Obj[["Enabled"]]<-FALSE
Obj<-Obj_ExpVar$Item("Kurtosis")
Obj[["Enabled"]]<-FALSE

}

